import type { Topic } from "@/types";

export const LEAF_TOPICS: Omit<Topic, "isMega">[] = [
  { id: "audio-quality", name: "Audio Quality", kind: "category" },
  { id: "overall-satisfaction", name: "Overall satisfaction", kind: "universal" },
  { id: "battery", name: "Battery", kind: "category" },
  { id: "price-value-for-money", name: "Price/Value for money", kind: "universal" },
  { id: "ergonomics", name: "Ergonomics", kind: "category" },
  { id: "performance", name: "Performance", kind: "category" },
  { id: "connectivity", name: "Connectivity", kind: "category" },
  { id: "ease-of-use", name: "Ease of use", kind: "universal" },
  { id: "quality", name: "Quality", kind: "universal" },
  { id: "is-it-recommended", name: "Is it recommended?", kind: "universal" },
  { id: "noise-cancellation", name: "Noise Cancellation", kind: "category" },
  { id: "usage-purpose", name: "Usage Purpose", kind: "universal" },
  { id: "size", name: "Size", kind: "universal" },
  { id: "comfortable", name: "Comfortable", kind: "category" },
  { id: "accessories", name: "Accessories", kind: "universal" },
  { id: "meets-expectations", name: "Meets expectations", kind: "universal" },
  { id: "returning-customer", name: "Returning customer", kind: "universal" },
  { id: "life-span", name: "Life span", kind: "universal" },
  { id: "music-listening-experience", name: "Music Listening Experience", kind: "category" },
  { id: "call-experience", name: "Call Experience", kind: "category" },
  { id: "return-and-refund", name: "Return & refund", kind: "universal" },
  { id: "bass", name: "Bass", kind: "category" },
  { id: "customer-service", name: "Customer service", kind: "universal" },
  { id: "compatibility", name: "Compatibility", kind: "universal" },
  { id: "volume", name: "Volume", kind: "category" },
  { id: "product-defect", name: "Product Defect", kind: "universal" },
  { id: "touch-control", name: "Touch Control", kind: "category" },
  { id: "waterproof", name: "Waterproof", kind: "category" },
  { id: "eartips", name: "Eartips", kind: "category" },
  { id: "audio-fidelity", name: "Audio Fidelity", kind: "category" },
  { id: "specs-comparison", name: "Specs Comparison", kind: "universal" },
  { id: "time-frequency-of-use", name: "Time/Frequency of use", kind: "universal" },
  { id: "customer-wishlist", name: "Customer Wishlist", kind: "universal" },
  { id: "microphone", name: "Microphone", kind: "category" },
  { id: "settings", name: "Settings", kind: "universal" },
  { id: "design", name: "Design", kind: "universal" },
  { id: "volume-control", name: "Volume Control", kind: "category" },
  { id: "shipping", name: "Shipping", kind: "universal" },
  { id: "gift-purposes", name: "Gift purposes", kind: "universal" },
  { id: "packaging", name: "Packaging", kind: "universal" },
  { id: "warranty", name: "Warranty", kind: "universal" },
  { id: "instructions", name: "Instructions", kind: "universal" },
  { id: "weight", name: "Weight", kind: "universal" },
  { id: "ambient-sounds", name: "Ambient Sounds", kind: "category" },
  { id: "treble", name: "Treble", kind: "category" },
  { id: "online-shopping", name: "Online shopping", kind: "universal" },
  { id: "portability", name: "Portability", kind: "universal" },
  { id: "material", name: "Material", kind: "universal" },
  { id: "audio-features", name: "Audio Features", kind: "category" },
  { id: "speaker-quality", name: "Speaker Quality", kind: "category" },
  { id: "midrange", name: "Midrange", kind: "category" },
  { id: "applications", name: "Applications", kind: "category" },
  { id: "color", name: "Color", kind: "universal" },
  { id: "loyalty", name: "Loyalty", kind: "universal" },
  { id: "audiophile", name: "Audiophile", kind: "category" },
  { id: "voice-recognition", name: "Voice Recognition", kind: "category" },
  { id: "stereo", name: "Stereo", kind: "category" },
  { id: "gaming-experience", name: "Gaming Experience", kind: "category" },
  { id: "item-availability", name: "Item availability", kind: "universal" },
  { id: "customization", name: "Customization", kind: "category" },
  { id: "radio", name: "Radio", kind: "category" },
  { id: "genuine", name: "Genuine", kind: "universal" },
  { id: "3d-surround-sound", name: "3D Surround Sound", kind: "category" },
  { id: "notifications", name: "Notifications", kind: "category" },
  { id: "smell", name: "Smell", kind: "universal" },
  { id: "manufacturing-country", name: "Manufacturing country", kind: "universal" },
];

export const TOPIC_WEIGHTS: Record<string, number> = {
  "audio-quality": 30,
  "overall-satisfaction": 27,
  battery: 20,
  "price-value-for-money": 17,
  ergonomics: 14,
  performance: 12,
  connectivity: 12,
  "ease-of-use": 8,
  quality: 8,
  "is-it-recommended": 8,
  "noise-cancellation": 8,
  "usage-purpose": 8,
  size: 6,
  comfortable: 10,
  accessories: 7,
  "meets-expectations": 6,
  "returning-customer": 6,
  "life-span": 5,
  "music-listening-experience": 5,
  "call-experience": 5,
  "return-and-refund": 4,
  bass: 4,
  "customer-service": 4,
  compatibility: 4,
  volume: 4,
  "product-defect": 4,
  "touch-control": 4,
  waterproof: 4,
  eartips: 4,
  "audio-fidelity": 3,
  "specs-comparison": 3,
  "time-frequency-of-use": 3,
  "customer-wishlist": 3,
  microphone: 2.2,
  settings: 2.2,
  design: 1.9,
  "volume-control": 1.7,
  shipping: 1.5,
  "gift-purposes": 1.3,
  packaging: 1.1,
  warranty: 0.96,
  instructions: 0.89,
  weight: 0.74,
  "ambient-sounds": 0.65,
  treble: 0.56,
  "online-shopping": 0.49,
  portability: 0.43,
  material: 0.37,
  "audio-features": 0.33,
  "speaker-quality": 0.28,
  midrange: 0.24,
  applications: 0.21,
  color: 0.18,
  loyalty: 0.16,
  audiophile: 0.13,
  "voice-recognition": 0.11,
  stereo: 0.1,
  "gaming-experience": 0.08,
  "item-availability": 0.07,
  customization: 0.06,
  radio: 0.05,
  genuine: 0.04,
  "3d-surround-sound": 0.04,
  notifications: 0.04,
  smell: 0.03,
  "manufacturing-country": 0.03,
};

export const SENTIMENT_HINTS: Record<string, number> = {
  "audio-quality": 81,
  "overall-satisfaction": 89,
  battery: 66,
  "price-value-for-money": 76,
  ergonomics: 69,
  performance: 66,
  connectivity: 59,
  "ease-of-use": 86,
  quality: 75,
  "is-it-recommended": 77,
  "noise-cancellation": 64,
  "usage-purpose": 77,
  size: 64,
  comfortable: 81,
  accessories: 70,
  "meets-expectations": 72,
  "returning-customer": 73,
  "life-span": 90,
  "music-listening-experience": 76,
  "call-experience": 90,
  "return-and-refund": 85,
  bass: 73,
  "customer-service": 73,
  compatibility: 75,
  volume: 90,
  "product-defect": 15,
  "touch-control": 77,
  waterproof: 62,
  eartips: 60,
  "audio-fidelity": 87,
  "specs-comparison": 75,
  "time-frequency-of-use": 74,
  "customer-wishlist": 19,
  microphone: 79,
  settings: 78,
  design: 87,
  "volume-control": 60,
  shipping: 55,
  "gift-purposes": 73,
  packaging: 67,
  warranty: 57,
  instructions: 52,
  weight: 76,
  "ambient-sounds": 87,
  treble: 82,
  "online-shopping": 79,
  portability: 49,
  material: 78,
  "audio-features": 71,
  "speaker-quality": 38,
  midrange: 73,
  applications: 79,
  color: 83,
  loyalty: 78,
  audiophile: 79,
  "voice-recognition": 60,
  stereo: 78,
  "gaming-experience": 44,
  "item-availability": 88,
  customization: 75,
  radio: 52,
  genuine: 49,
  "3d-surround-sound": 49,
  notifications: 62,
  smell: 15,
  "manufacturing-country": 63,
};

export const MEGA_TOPICS: Topic[] = [
  {
    id: "mega-sound-signature",
    name: "Sound Signature",
    kind: "category",
    isMega: true,
    memberTopicIds: ["bass", "treble", "midrange", "stereo", "audio-fidelity", "3d-surround-sound"],
  },
  {
    id: "mega-fit-comfort",
    name: "Fit & Comfort",
    kind: "category",
    isMega: true,
    memberTopicIds: ["ergonomics", "comfortable", "eartips", "size", "weight"],
  },
  {
    id: "mega-post-purchase",
    name: "Post-Purchase Experience",
    kind: "universal",
    isMega: true,
    memberTopicIds: [
      "shipping",
      "packaging",
      "return-and-refund",
      "warranty",
      "customer-service",
      "item-availability",
    ],
  },
];

export function allTopics(): Topic[] {
  return [
    ...LEAF_TOPICS.map((t) => ({ ...t, isMega: false })),
    ...MEGA_TOPICS,
  ];
}

export const RARE_TOPIC_ID = "smell";
